"""
edgedash/skills.py — Skill name canonicalisation (steering rules 22-23).

NO LLM calls in the core functions. NO network. NO model judgement.
All canonicalisation is pure: same input → same output, every time.

The ONE permitted model call is in _run_suggest_aliases(), which is an
interactive helper only.  It may SUGGEST groupings but writes nothing.

Public API:
    canonical(raw: str, aliases: dict[str, str]) -> str

CLI:
    python -m edgedash.skills --audit           [--db path] [--config path]
    python -m edgedash.skills --suggest-aliases [--db path] [--config path]
"""

from __future__ import annotations

import re


# ---------------------------------------------------------------------------
# canonical()  — pure function
# ---------------------------------------------------------------------------


def canonical(raw: str, aliases: dict[str, str]) -> str:
    """
    Normalise a raw skill string to its canonical form.

    Steps (in order):
      1. Lowercase and strip outer whitespace.
      2. Strip surrounding punctuation (quotes, brackets, hyphens, dots …).
      3. Drop a single parenthetical qualifier, e.g. "kubernetes (eks)" →
         "kubernetes".  Keeps the base term; the qualifier is noise for
         gap-ranking purposes.
      4. Collapse any run of internal whitespace to a single space.
      5. Apply the caller-supplied alias map (exact match after steps 1-4).

    Returns the canonical string, or an empty string if the input is empty
    after normalisation.  Never raises.

    Parameters
    ----------
    raw     : Raw skill string from the extractor (may be messy).
    aliases : Flat dict mapping alias → canonical.  Keys should already be
              in the normalised form produced by steps 1-4 so that the alias
              lookup is reliable.  This dict comes from config.yaml and is
              owned by the user — never generated by a model.
    """
    if not isinstance(raw, str):
        return ""

    # Step 1 – lowercase + strip outer whitespace
    s = raw.strip().lower()
    if not s:
        return ""

    # Step 2 – drop trailing parenthetical qualifier BEFORE stripping
    # surrounding punctuation so the closing ) is still present.
    # Matches e.g. "kubernetes (eks)", "python (3.x)", "aws (ec2, s3)"
    s = re.sub(r"\s*\([^)]*\)\s*$", "", s).strip()
    if not s:
        return ""

    # Step 3 – strip surrounding punctuation (non-alphanumeric, non-space)
    # Excludes ( and ) because the parenthetical case was handled above.
    s = s.strip(r"""!"#$%&'*+,-./:;<=>?@[\]^_`{|}~""")
    s = s.strip()
    if not s:
        return ""

    # Step 4 – collapse internal whitespace
    s = re.sub(r"\s+", " ", s)

    # Step 5 – alias map lookup (exact, after normalisation)
    return aliases.get(s, s)



# ---------------------------------------------------------------------------
# CLI: --audit
# ---------------------------------------------------------------------------


def _run_audit(db_path: str, config_path: str) -> None:
    """
    Read every extraction_cache row, unpack required_skills + nice_to_have,
    and print:
      - Top 40 raw skill strings with counts and their canonical form.
      - All raw strings seen exactly once (typos / junk / full sentences).
    """
    import json
    import sqlite3
    from collections import Counter
    from pathlib import Path

    import yaml

    # ---- load alias map from config ----
    cfg_file = Path(config_path)
    aliases: dict[str, str] = {}
    if cfg_file.is_file():
        with open(cfg_file, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
        raw_aliases: dict = data.get("skill_aliases", {})
        # values in the yaml may be a single string or a list of strings;
        # normalise to {alias_str: canonical_str}
        for canon, alias_entry in raw_aliases.items():
            if isinstance(alias_entry, list):
                for a in alias_entry:
                    aliases[str(a).strip().lower()] = str(canon).strip().lower()
            else:
                aliases[str(alias_entry).strip().lower()] = str(canon).strip().lower()
    else:
        print(f"[WARN] config file not found at '{config_path}' — running with empty alias map.\n")

    # ---- read extraction_cache ----
    db = Path(db_path)
    if not db.is_file():
        print(f"[ERROR] Database not found at '{db_path}'.")
        return

    conn = sqlite3.connect(str(db))
    try:
        rows = conn.execute(
            "SELECT extraction_json FROM extraction_cache"
        ).fetchall()
    except sqlite3.OperationalError as exc:
        print(f"[ERROR] Could not read extraction_cache: {exc}")
        conn.close()
        return
    conn.close()

    counter: Counter[str] = Counter()
    for (json_str,) in rows:
        try:
            obj = json.loads(json_str)
        except (json.JSONDecodeError, TypeError):
            continue
        for skill in obj.get("required_skills") or []:
            if isinstance(skill, str) and skill.strip():
                counter[skill.strip().lower()] += 1
        for skill in obj.get("nice_to_have") or []:
            if isinstance(skill, str) and skill.strip():
                counter[skill.strip().lower()] += 1

    if not counter:
        print("No skill data found in extraction_cache. Run the scorer first.")
        return

    total_unique = len(counter)
    total_occurrences = sum(counter.values())

    print("=" * 70)
    print("EDGEDASH SKILL AUDIT")
    print(f"  Cache rows read : {len(rows)}")
    print(f"  Unique raw terms: {total_unique}")
    print(f"  Total occurrences: {total_occurrences}")
    print(f"  Alias map entries: {len(aliases)}")
    print("=" * 70)

    # ---- Top 40 ----
    print("\n── TOP 40 RAW SKILLS ─────────────────────────────────────────────\n")
    print(f"  {'COUNT':>5}  {'RAW SKILL':<35}  CANONICAL")
    print(f"  {'─────':>5}  {'─' * 35}  {'─' * 30}")

    for raw_skill, count in counter.most_common(40):
        canon = canonical(raw_skill, aliases)
        marker = "  (aliased)" if canon != raw_skill else ""
        print(f"  {count:>5}  {raw_skill:<35}  {canon}{marker}")

    # ---- Singletons ----
    singletons = sorted(raw for raw, cnt in counter.items() if cnt == 1)
    print(f"\n── SINGLETONS ({len(singletons)} terms seen exactly once) ───────────────────\n")
    if singletons:
        print("  These are candidates for typos, junk phrases, or missing aliases.\n")
        for s in singletons:
            canon = canonical(s, aliases)
            marker = f"  → {canon}" if canon != s else ""
            print(f"  {s}{marker}")
    else:
        print("  (none)")

    print("\n" + "=" * 70)
    print("To add a missing alias: edit skill_aliases in config.yaml.")
    print("=" * 70 + "\n")


# ---------------------------------------------------------------------------
# CLI: --suggest-aliases  (the ONE permitted model call in this file)
# ---------------------------------------------------------------------------

# Response schema for the LLM — wrapped in an object because complete_json
# requires a top-level object, not an array.
_SUGGEST_SCHEMA: dict = {
    "type": "object",
    "required": ["groupings"],
    "properties": {
        "groupings": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["canonical", "variants", "confidence"],
                "properties": {
                    "canonical": {"type": "string"},
                    "variants":  {"type": "array", "items": {"type": "string"}},
                    "confidence": {"type": "string"},  # "high" | "low"
                },
            },
        }
    },
}

_SUGGEST_PROMPT = """\
You are reviewing a list of skill strings extracted from job descriptions.
Some strings may refer to the same underlying skill under different names
or abbreviations.

Your task: propose groupings of strings that clearly refer to the SAME
skill. Only group strings you are highly confident are synonyms.

Critical rules:
- Do NOT merge skills that are genuinely distinct, even if related.
  (e.g. node.js and javascript are different skills; do not merge them)
- Do NOT merge skills with overlapping but different scopes.
  (e.g. "data analysis" and "data engineering" are not the same)
- If you are unsure whether two strings are the same skill, use
  confidence "low" — the human will decide.
- Do NOT rename or reinterpret. Canonical must be one of the strings
  you were given.
- Omit any string that clearly stands alone with no synonyms.

For each grouping, pick the most standard/readable string as canonical
and list the others as variants.

Skill strings to analyse:
{skill_list}
"""


def _run_suggest_aliases(db_path: str, config_path: str) -> None:
    """
    Collect unaliased canonical skills from the DB, call the model ONCE to
    propose groupings, then print ready-to-paste YAML.

    This is the ONLY model call in this file.
    It writes NOTHING — not config.yaml, not the database, not any file.
    """
    import io as _io
    import json
    import sqlite3
    import sys
    from collections import Counter
    from pathlib import Path

    import yaml

    from edgedash import llm

    # ── Ensure Unicode on Windows ────────────────────────────────────────
    if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
        sys.stdout = _io.TextIOWrapper(
            sys.stdout.buffer, encoding="utf-8", errors="replace"
        )

    # ── Load existing alias map ──────────────────────────────────────────
    cfg_file = Path(config_path)
    aliases: dict[str, str] = {}      # alias → canonical
    canonical_to_aliases: dict[str, list[str]] = {}  # canonical → [aliases]

    if cfg_file.is_file():
        with open(cfg_file, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
        raw_map: dict = data.get("skill_aliases", {})
        for canon_key, alias_entry in raw_map.items():
            ck = str(canon_key).strip().lower()
            entries = alias_entry if isinstance(alias_entry, list) else [alias_entry]
            canonical_to_aliases[ck] = [str(a).strip().lower() for a in entries]
            for a in entries:
                aliases[str(a).strip().lower()] = ck
    else:
        print(f"[WARN] config not found at '{config_path}' — alias map is empty.\n")

    # All strings already covered by the alias map (both sides)
    already_mapped: set[str] = set(aliases.keys()) | set(canonical_to_aliases.keys())

    # ── Collect skills from extraction_cache ─────────────────────────────
    db = Path(db_path)
    if not db.is_file():
        print(f"[ERROR] Database not found at '{db_path}'.")
        return

    conn = sqlite3.connect(str(db))
    try:
        rows = conn.execute(
            "SELECT extraction_json FROM extraction_cache"
        ).fetchall()
    except sqlite3.OperationalError as exc:
        print(f"[ERROR] Could not read extraction_cache: {exc}")
        conn.close()
        return
    conn.close()

    counter: Counter[str] = Counter()
    for (json_str,) in rows:
        try:
            obj = json.loads(json_str)
        except (json.JSONDecodeError, TypeError):
            continue
        for field in ("required_skills", "nice_to_have"):
            for skill in obj.get(field) or []:
                if isinstance(skill, str) and skill.strip():
                    canon_form = canonical(skill, aliases)
                    if canon_form:
                        counter[canon_form] += 1

    # Keep only skills NOT already in the alias map, seen at least once
    candidates: list[str] = sorted(
        s for s in counter if s not in already_mapped
    )

    if not candidates:
        print("\nNo unaliased skills found in the database.")
        print("Everything is either already in the alias map or the DB is empty.\n")
        return

    # ── Warning header ───────────────────────────────────────────────────
    print()
    print("=" * 72)
    print("  ALIAS SUGGESTIONS  —  REVIEW REQUIRED BEFORE USE")
    print("=" * 72)
    print()
    print("  WARNING: These are MODEL SUGGESTIONS. They need your review.")
    print("  Merging distinct skills is WORSE than leaving them separate.")
    print("  If you are unsure about a grouping, do not add it.")
    print("  Paste only the entries you are confident about into config.yaml.")
    print()
    print(f"  Sending {len(candidates)} unaliased skills to the model — ONE call.")
    print()

    # ── Single LLM call ─────────────────────────────────────────────────
    skill_list_str = "\n".join(f"- {s}" for s in candidates)
    prompt = _SUGGEST_PROMPT.format(skill_list=skill_list_str)

    try:
        response = llm.complete_json(prompt, _SUGGEST_SCHEMA)
    except llm.LLMError as exc:
        print(f"[ERROR] Model call failed: {exc}")
        return

    groupings: list[dict] = response.get("groupings") or []

    if not groupings:
        print("  The model found no grouping suggestions.\n")
        return

    # ── Conflict detection ───────────────────────────────────────────────
    # A conflict = the model wants to merge two strings that I have already
    # chosen to keep SEPARATE (i.e. both appear as distinct canonical keys
    # in my alias map).
    conflicts: list[tuple[dict, str]] = []
    clean: list[dict] = []

    for group in groupings:
        canon_suggestion = str(group.get("canonical", "")).strip().lower()
        variants = [str(v).strip().lower() for v in (group.get("variants") or [])]
        all_in_group = {canon_suggestion} | set(variants)

        # Which of these does my map already treat as separate canonicals?
        conflicting = all_in_group & set(canonical_to_aliases.keys())

        if len(conflicting) > 1:
            # Two or more members are already separate canonical entries
            conflict_msg = (
                f"merges {sorted(conflicting)}, which are separate "
                f"entries in your alias map"
            )
            conflicts.append((group, conflict_msg))
        else:
            clean.append(group)

    # ── Print conflicts loudly ───────────────────────────────────────────
    if conflicts:
        print("  !! CONFLICTS WITH YOUR EXISTING ALIAS MAP !!")
        print("  The model proposed groupings that contradict your choices.")
        print("  These are printed for information only — do NOT paste them.")
        print()
        for group, reason in conflicts:
            print(f"  CONFLICT: {reason}")
            print(f"    Model proposed canonical : {group.get('canonical')}")
            print(f"    Model proposed variants  : {group.get('variants')}")
            print(f"    Confidence               : {group.get('confidence')}")
            print()

    # ── Print ready-to-paste YAML for clean suggestions ──────────────────
    if not clean:
        print("  No conflict-free suggestions to show.\n")
        return

    print("=" * 72)
    print("  READY-TO-PASTE YAML  (add under skill_aliases: in config.yaml)")
    print("  Review each entry before pasting. Delete any you disagree with.")
    print("=" * 72)
    print()

    for group in clean:
        canon_suggestion = str(group.get("canonical", "")).strip().lower()
        variants = [str(v).strip().lower() for v in (group.get("variants") or [])]
        conf = str(group.get("confidence", "low")).lower()

        if not canon_suggestion or not variants:
            continue

        conf_comment = "  # high confidence" if conf == "high" else "  # LOW CONFIDENCE — verify before adding"
        print(f"  {canon_suggestion}:{conf_comment}")
        for v in variants:
            print(f"    - {v}")
        print()

    print("=" * 72)
    print("  These suggestions are read-only. Nothing has been written.")
    print("  To apply: copy the entries above into config.yaml under skill_aliases.")
    print("=" * 72)
    print()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Skill canonicalisation utilities for EdgeDash."
    )
    parser.add_argument(
        "--audit",
        action="store_true",
        help="Print skill frequency report from the database (read-only).",
    )
    parser.add_argument(
        "--suggest-aliases",
        action="store_true",
        dest="suggest_aliases",
        help=(
            "Ask the model to suggest alias groupings for unaliased skills. "
            "ONE model call. Prints YAML only — writes nothing."
        ),
    )
    parser.add_argument(
        "--db",
        default="edgedash.db",
        metavar="PATH",
        help="Path to the SQLite database (default: edgedash.db).",
    )
    parser.add_argument(
        "--config",
        default="config.yaml",
        metavar="PATH",
        help="Path to config.yaml (default: config.yaml).",
    )

    args = parser.parse_args()

    if args.audit:
        _run_audit(db_path=args.db, config_path=args.config)
    elif args.suggest_aliases:
        _run_suggest_aliases(db_path=args.db, config_path=args.config)
    else:
        parser.print_help()
